### ISSUE TITLE
Links in settings view are not working

### ISSUE THREAD

**Issue by pestotoast** [arborwallet/arbor-wallet#32]
In the settings view the buttons for 'View Privacy Policy' and the link to the discord channel don't work. (Android 11)

[Screenshot](https://i.imgur.com/gcdgb9G.jpg)

**Comment by scotopic** [comment]
What happens when you tap on the links?

**Comment by pestotoast** [comment]
Yes the buttons still do not work. I tested it on a Samsung Galaxy S10 with Android 11.

**Comment by scotopic** [comment]
Sadly, this service/wallet has been shutdown. Try using your mnemonic in a different wallet either official Chia wallet or Evergreen mobile wallet.
