### ISSUE TITLE
Bug: Android Beta, Transaction History

### ISSUE THREAD

**Issue by feurer98** [arborwallet/arbor-wallet#39]
I have made test sweatings and found that the course is difficult to follow. Over a longer period of time, the sweatings are no longer sorted correctly.

### Expected:
11:40 AM
10:20 AM
10:00 AM
09:45 AM
09:30 AM
09:00 AM
08:54 AM
08:30 AM
07:20 AM

### Fact:
09:45 AM
09:30 AM
09:00 AM
11:40 AM
10:20 AM
10:00 AM

See screenshot
(I am also pleased when everything works as promised. #34 )
---

![image](https://user-images.githubusercontent.com/45851500/139825080-61e5938b-6e99-436b-af31-1fe3a04efd4e.png)

**Comment by scotopic** [comment]
https://github.com/Digital-Farming-Initiative/arbor-wallet/pull/42 should fix it, we'll update this issue once we have a new release
